### PR TITLE
Renamed storage paths.

### PR DESCRIPTION
**Pull request by 320kg**
AUR package up and running now, expect me to submit it

### CODE REVIEW

**Comment by fokkonaut** [comment]
That seems wrong to me, rather keep it in vanilla paths

**Comment by 320kg** [comment]
@fokkonaut 
1. `cmake install` installs in /usr/share/F-Client, not /usr/share/teeworlds, so the game can't find it and it results in the following: Знімок_20241228_150952
2. We forked the assets anyway

Happy new year btw

**Comment by 320kg** [comment]
Also, if we rename/remove the server binary it would allow one to install both clients without conflict

**Comment by fokkonaut** [comment]
Thanks for explaining, and a happy new year aswell :)

**Pull request merged**
